# Generated by Django 3.2.14 on 2022-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agri',
            name='img',
            field=models.ImageField(default='asadadad', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
